language: rust
sudo: false

rust:
- nightly
- beta
- stable
- 1.42.0

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script:
- travis-cargo build
- travis-cargo build --features alloc
- travis-cargo test --features alloc
- travis-cargo build --no-default-features
- travis-cargo build --no-default-features --features alloc
- travis-cargo build --no-default-features --features memchr
- travis-cargo build --no-default-features --features libc
- travis-cargo doc -- --no-deps

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=

notifications:
  email: false
